version: '1.0'
services:
  pipeline:
    image: pipeline
    container_name: pipeline
    build:
      context: ./
      dockerfile: ./containers/pipeline/Dockerfile
    volumes:
      - ./:/code
    environment:
      WAREHOUSE_USER: ${POSTGRES_USER}
      WAREHOUSE_PASSWORD: ${POSTGRES_PASSWORD}
      WAREHOUSE_DB: ${POSTGRES_DB}
      WAREHOUSE_HOST: ${POSTGRES_HOST}
      WARREHOUSE_PORT: ${POSTGRES_PORT}